export const mockProducts = [
    {
        id: 1,
        name: "Chamarra urbana",
        price: "1.82",
        stock: "2",
        size: "M",
        status: "PUBLISHED",
        categoryId: 1,
        description: "Prenda para el frío.",
        img: "imagen.com",
    },
    {
        id: 2,
        name: "Sueter de punto",
        price: "2.50",
        stock: "5",
        size: "L",
        status: "PUBLISHED",
        categoryId: 2,
        description: "Prenda para vestir.",
        img: "imagen2.com",
    },
    {
        id: 3,
        name: "Impermeable",
        price: "2.50",
        stock: "5",
        size: "L",
        status: "PUBLISHED",
        categoryId: 2,
        description: "Prenda para vestir.",
        img: "imagen2.com",
    },
    {
        id: 4,
        name: "Sudadera",
        price: "2.50",
        stock: "5",
        size: "L",
        status: "PUBLISHED",
        categoryId: 1,
        description: "Prenda para vestir.",
        img: "imagen2.com",
    }
];
